export const SEARCH_VALUE_CHANGED = 'SEARCH_VALUE_CHANGED';
export const CHARACTERS_REQUESTED = 'CHARACTERS_REQUESTED';
export const SEARCH_RESULTS_FULFILLED = 'SEARCH_RESULTS_FULFILLED';
export const SEARCH_RESULTS_ERRORED = 'SEARCH_RESULTS_ERRORED';
export const CHARACTER_BOOKMARK = 'CHARACTER_BOOKMARK';
export const CHANGE_PAGE = 'CHANGE_PAGE';
